/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The primary category for this transaction
 */
export type ExpenseCategory =
  | "housing"
  | "food"
  | "transport"
  | "utilities"
  | "healthcare"
  | "entertainment"
  | "education"
  | "personal"
  | "shopping"
  | "other";
/**
 * Confidence score from 0.0 to 1.0
 */
export type Confidence = number;
/**
 * Brief explanation of why this category was chosen
 */
export type Reasoning = string;

/**
 * Schema for categorizing a bank transaction description.
 */
export interface TransactionCategorizationSchema {
  category: ExpenseCategory;
  confidence: Confidence;
  reasoning: Reasoning;
  [k: string]: unknown;
}
