/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ExpenseCategory =
  | "housing"
  | "food"
  | "transport"
  | "utilities"
  | "healthcare"
  | "entertainment"
  | "education"
  | "personal"
  | "shopping"
  | "other";
export type AnomalySeverity = "low" | "medium" | "high";
/**
 * Human-readable description of the anomaly, e.g., 'Utilities spiked by 45%'
 */
export type Description = string;
/**
 * Actionable advice for the user, e.g., 'Check for leaking faucets'
 */
export type RecommendedAction = string;
export type Anomalies = AnomalyInsight[];

/**
 * Full report containing all detected spending anomalies.
 */
export interface AnomalyReportSchema {
  anomalies: Anomalies;
  [k: string]: unknown;
}
/**
 * Represents a single detected anomaly with AI reasoning.
 */
export interface AnomalyInsight {
  category: ExpenseCategory;
  severity: AnomalySeverity;
  description: Description;
  recommended_action: RecommendedAction;
  [k: string]: unknown;
}
