/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The classified type of the document
 */
export type DocumentType = "LOAN" | "BANK_STATEMENT" | "UNKNOWN";
/**
 * 'single' if one loan account, 'multi' if multiple distinct loan accounts with different account numbers. Summaries/totals of the same account are NOT separate loans.
 */
export type LoanStructure = "single" | "multi";
/**
 * The name of the loan or lender
 */
export type Name = string;
/**
 * The original principal amount of the loan
 */
export type Principal = number;
/**
 * The annual interest rate as a percentage (e.g., 12.0)
 */
export type InterestRate = number;
/**
 * The Effective Interest Rate (EIR) per year as a percentage, if explicitly stated in the document. Different from interest_rate for add-on loans.
 */
export type AnnualEir = number | null;
/**
 * The monthly or per-period installment amount. Return null if not stated explicitly per individual loan.
 */
export type InstallmentAmount = number | null;
/**
 * Explicit loan term in months. Return null if no numeric term is stated in the document. Do NOT infer from repayment plan names or dates.
 */
export type DurationMonths = number | null;
/**
 * The start date of the loan in YYYY-MM-DD format
 */
export type StartDate = string | null;
/**
 * The ISO 4217 currency code (e.g., USD, PHP, SGD)
 */
export type Currency = string;
/**
 * The type of interest calculation
 */
export type LoanInterestType = "Standard Amortized" | "Interest-Only" | "Add-on Interest" | "Fixed Principal";
/**
 * The name of the lending institution
 */
export type Lender = string | null;
/**
 * Confidence score from 0.0 to 1.0
 */
export type Confidence = number;
/**
 * Brief explanation of the extraction results
 */
export type Reasoning = string;
/**
 * The 1-indexed page number where the information was found
 */
export type Page = number | null;
/**
 * The exact text snippet used as source context
 */
export type Snippet = string | null;
export type Loans = SingleLoanExtractionSchema[];
/**
 * Master account number tying all loans together, if present.
 */
export type AccountNumber = string | null;
/**
 * Account-level monthly payment (e.g. 'Regular Monthly Payment Amount'). Set when the document shows a combined payment for all loans with no per-loan breakdown.
 */
export type AccountMonthlyPayment = number | null;
/**
 * The name of the account or institution
 */
export type AccountName = string;
/**
 * The date range covered by the statement
 */
export type StatementPeriod = string;
/**
 * The transaction date in YYYY-MM-DD format
 */
export type Date = string;
/**
 * The transaction description or merchant name
 */
export type Description = string;
/**
 * The transaction amount (negative for expenses, positive for income/deposits)
 */
export type Amount = number;
export type Transactions = TransactionExtractionItem[];
/**
 * Confidence score from 0.0 to 1.0
 */
export type Confidence1 = number;
/**
 * Brief explanation of the extraction results
 */
export type Reasoning1 = string;
/**
 * Classification confidence
 */
export type Confidence2 = number;
/**
 * Reasoning for classification
 */
export type Reasoning2 = string;
/**
 * Status of the parallel verification/cross-check process.
 */
export type VerificationStatus = "verified" | "skipped" | "failed";
/**
 * A human-readable message explaining reliability issues (e.g., rate limits).
 */
export type UserFriendlyMessage = string | null;
/**
 * Non-fatal warnings encountered during extraction.
 */
export type ExtractionWarnings = string[];
/**
 * Technical metadata about the extraction process (char counts, method)
 */
export type OcrTelemetry = {
  [k: string]: unknown;
} | null;

/**
 * Polymorphic response for unified document processing.
 */
export interface UnifiedDocumentResponse {
  document_type: DocumentType;
  loan_structure: LoanStructure;
  /**
   * Populated when loan_structure is 'single'.
   */
  loan_data?: SingleLoanExtractionSchema | null;
  /**
   * Populated when loan_structure is 'multi'.
   */
  multi_loan_data?: MultiLoanExtractionSchema | null;
  /**
   * Populated if document_type is BANK_STATEMENT
   */
  statement_data?: StatementExtractionSchema | null;
  confidence?: Confidence2;
  reasoning?: Reasoning2;
  verification_status?: VerificationStatus;
  user_friendly_message?: UserFriendlyMessage;
  extraction_warnings?: ExtractionWarnings;
  ocr_telemetry?: OcrTelemetry;
  [k: string]: unknown;
}
/**
 * Schema for extracting loan details from a document.
 */
export interface SingleLoanExtractionSchema {
  name: Name;
  principal: Principal;
  interest_rate: InterestRate;
  annual_eir?: AnnualEir;
  installment_amount?: InstallmentAmount;
  duration_months?: DurationMonths;
  start_date?: StartDate;
  currency?: Currency;
  interest_type?: LoanInterestType;
  lender?: Lender;
  confidence?: Confidence;
  reasoning?: Reasoning;
  /**
   * Source location for the primary extracted data (page + snippet)
   */
  provenance?: Provenance | null;
  [k: string]: unknown;
}
/**
 * Metadata linking extracted data back to its source in the document.
 */
export interface Provenance {
  page?: Page;
  snippet?: Snippet;
  [k: string]: unknown;
}
/**
 * Schema for documents containing multiple distinct loan accounts.
 */
export interface MultiLoanExtractionSchema {
  loans: Loans;
  account_number?: AccountNumber;
  account_monthly_payment?: AccountMonthlyPayment;
  [k: string]: unknown;
}
/**
 * Structured extraction of multiple transactions from a bank statement.
 */
export interface StatementExtractionSchema {
  account_name: AccountName;
  statement_period: StatementPeriod;
  transactions: Transactions;
  confidence?: Confidence1;
  reasoning?: Reasoning1;
  [k: string]: unknown;
}
/**
 * A single transaction extracted from a bank statement.
 */
export interface TransactionExtractionItem {
  date: Date;
  description: Description;
  amount: Amount;
  /**
   * Source provenance for this transaction
   */
  provenance?: Provenance | null;
  [k: string]: unknown;
}
