/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The name of the loan or lender
 */
export type Name = string;
/**
 * The original principal amount of the loan
 */
export type Principal = number;
/**
 * The annual interest rate as a percentage (e.g., 12.0)
 */
export type InterestRate = number;
/**
 * The Effective Interest Rate (EIR) per year as a percentage, if explicitly stated in the document. Different from interest_rate for add-on loans.
 */
export type AnnualEir = number | null;
/**
 * The monthly or per-period installment amount. Return null if not stated explicitly per individual loan.
 */
export type InstallmentAmount = number | null;
/**
 * Explicit loan term in months. Return null if no numeric term is stated in the document. Do NOT infer from repayment plan names or dates.
 */
export type DurationMonths = number | null;
/**
 * The start date of the loan in YYYY-MM-DD format
 */
export type StartDate = string | null;
/**
 * The ISO 4217 currency code (e.g., USD, PHP, SGD)
 */
export type Currency = string;
/**
 * The type of interest calculation
 */
export type LoanInterestType = "Standard Amortized" | "Interest-Only" | "Add-on Interest" | "Fixed Principal";
/**
 * The name of the lending institution
 */
export type Lender = string | null;
/**
 * Confidence score from 0.0 to 1.0
 */
export type Confidence = number;
/**
 * Brief explanation of the extraction results
 */
export type Reasoning = string;
/**
 * The 1-indexed page number where the information was found
 */
export type Page = number | null;
/**
 * The exact text snippet used as source context
 */
export type Snippet = string | null;

/**
 * Schema for extracting loan details from a document.
 */
export interface SingleLoanExtractionSchema {
  name: Name;
  principal: Principal;
  interest_rate: InterestRate;
  annual_eir?: AnnualEir;
  installment_amount?: InstallmentAmount;
  duration_months?: DurationMonths;
  start_date?: StartDate;
  currency?: Currency;
  interest_type?: LoanInterestType;
  lender?: Lender;
  confidence?: Confidence;
  reasoning?: Reasoning;
  /**
   * Source location for the primary extracted data (page + snippet)
   */
  provenance?: Provenance | null;
  [k: string]: unknown;
}
/**
 * Metadata linking extracted data back to its source in the document.
 */
export interface Provenance {
  page?: Page;
  snippet?: Snippet;
  [k: string]: unknown;
}
