/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The classified type of the document
 */
export type DocumentType = "LOAN" | "BANK_STATEMENT" | "UNKNOWN";
/**
 * The name of the loan or lender
 */
export type Name = string;
/**
 * The original principal amount of the loan
 */
export type Principal = number;
/**
 * The annual interest rate as a percentage (e.g., 12.0)
 */
export type InterestRate = number;
/**
 * The monthly or per-period installment amount
 */
export type InstallmentAmount = number;
/**
 * The total duration of the loan in months
 */
export type DurationMonths = number;
/**
 * The start date of the loan in YYYY-MM-DD format
 */
export type StartDate = string | null;
/**
 * The ISO 4217 currency code (e.g., PHP, USD, SGD)
 */
export type Currency = string;
/**
 * The type of interest calculation
 */
export type LoanInterestType = "Standard Amortized" | "Interest-Only" | "Add-on Interest" | "Fixed Principal";
/**
 * The name of the lending institution
 */
export type Lender = string | null;
/**
 * Confidence score from 0.0 to 1.0
 */
export type Confidence = number;
/**
 * Brief explanation of the extraction results
 */
export type Reasoning = string;
/**
 * The name of the account or institution
 */
export type AccountName = string;
/**
 * The date range covered by the statement
 */
export type StatementPeriod = string;
/**
 * The transaction date in YYYY-MM-DD format
 */
export type Date = string;
/**
 * The transaction description or merchant name
 */
export type Description = string;
/**
 * The transaction amount (negative for expenses, positive for income/deposits)
 */
export type Amount = number;
export type Transactions = TransactionExtractionItem[];
/**
 * Confidence score from 0.0 to 1.0
 */
export type Confidence1 = number;
/**
 * Brief explanation of the extraction results
 */
export type Reasoning1 = string;
/**
 * Classification confidence
 */
export type Confidence2 = number;
/**
 * Reasoning for classification
 */
export type Reasoning2 = string;

/**
 * Polymorphic response for unified document processing.
 */
export interface UnifiedDocumentResponse {
  document_type: DocumentType;
  /**
   * Populated if document_type is LOAN
   */
  loan_data?: LoanExtractionSchema | null;
  /**
   * Populated if document_type is BANK_STATEMENT
   */
  statement_data?: StatementExtractionSchema | null;
  confidence?: Confidence2;
  reasoning?: Reasoning2;
  [k: string]: unknown;
}
/**
 * Schema for extracting loan details from a document.
 */
export interface LoanExtractionSchema {
  name: Name;
  principal: Principal;
  interest_rate: InterestRate;
  installment_amount: InstallmentAmount;
  duration_months: DurationMonths;
  start_date?: StartDate;
  currency?: Currency;
  interest_type?: LoanInterestType;
  lender?: Lender;
  confidence?: Confidence;
  reasoning?: Reasoning;
  [k: string]: unknown;
}
/**
 * Structured extraction of multiple transactions from a bank statement.
 */
export interface StatementExtractionSchema {
  account_name: AccountName;
  statement_period: StatementPeriod;
  transactions: Transactions;
  confidence?: Confidence1;
  reasoning?: Reasoning1;
  [k: string]: unknown;
}
/**
 * A single transaction extracted from a bank statement.
 */
export interface TransactionExtractionItem {
  date: Date;
  description: Description;
  amount: Amount;
  [k: string]: unknown;
}
