/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The name of the loan or lender
 */
export type Name = string;
/**
 * The original principal amount of the loan
 */
export type Principal = number;
/**
 * The annual interest rate as a percentage (e.g., 12)
 */
export type InterestRate = number;
/**
 * The monthly or per-period installment amount
 */
export type InstallmentAmount = number | null;
/**
 * The total duration of the loan in months
 */
export type DurationMonths = number;
/**
 * The start date of the loan in YYYY-MM-DD format
 */
export type StartDate = string | null;
/**
 * The ISO 4217 currency code (e.g., PHP, USD, SGD)
 */
export type Currency = string;
/**
 * The type of interest calculation
 */
export type LoanInterestType = "Standard Amortized" | "Interest-Only" | "Add-on Interest" | "Fixed Principal";
/**
 * The name of the lending institution
 */
export type Lender = string | null;

/**
 * Schema for extracting loan details from a document.
 */
export interface LoanExtractionSchema {
  name: Name;
  principal: Principal;
  interest_rate: InterestRate;
  installment_amount?: InstallmentAmount;
  duration_months: DurationMonths;
  start_date?: StartDate;
  currency?: Currency;
  interest_type?: LoanInterestType;
  lender?: Lender;
  [k: string]: unknown;
}
