import { LegalLayout } from '~/components/legal/LegalLayout';

export default function TermsPage() {
  return (
    <LegalLayout title="Terms of Service" lastUpdated="May 7, 2026">
      <section className="space-y-4">
        <h2 className="text-sm font-black uppercase tracking-widest text-gray-400">1. Acceptance of Terms</h2>
        <p>
          By accessing or using StashFlow, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-sm font-black uppercase tracking-widest text-gray-400">2. Financial Disclaimer</h2>
        <div className="bg-amber-50 border border-amber-100 rounded-2xl p-6 text-amber-900 font-medium">
          <p>
            <strong>StashFlow is not a financial advisor.</strong> The platform provides tools for data organization and analysis. Any insights or projections generated by our AI are for informational purposes only and do not constitute financial, legal, or tax advice. You are responsible for your own financial decisions.
          </p>
        </div>
      </section>

      <section className="space-y-4">
        <h2 className="text-sm font-black uppercase tracking-widest text-gray-400">3. User Responsibilities</h2>
        <p>
          When using StashFlow, you agree that:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>You will provide accurate information to the best of your knowledge.</li>
          <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
          <li>You will not use the service for any illegal or unauthorized purposes.</li>
          <li>You own or have the necessary rights to any documents you upload for parsing.</li>
        </ul>
      </section>

      <section className="space-y-4">
        <h2 className="text-sm font-black uppercase tracking-widest text-gray-400">4. Service Availability</h2>
        <p>
          While we strive for 100% uptime, StashFlow is provided "as is" and "as available." We do not guarantee that the service will be uninterrupted or error-free. We reserve the right to modify or discontinue features at any time.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-sm font-black uppercase tracking-widest text-gray-400">5. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, StashFlow Inc. shall not be liable for any indirect, incidental, or consequential damages resulting from your use of the platform, including financial loss or data loss.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-sm font-black uppercase tracking-widest text-gray-400">6. Termination</h2>
        <p>
          We reserve the right to suspend or terminate your account if you violate these terms. You may delete your account and stop using the service at any time via the Settings dashboard.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-sm font-black uppercase tracking-widest text-gray-400">7. Changes to Terms</h2>
        <p>
          We may update these Terms of Service from time to time. Continued use of the platform after changes are posted constitutes your acceptance of the new terms.
        </p>
      </section>
    </LegalLayout>
  );
}
